number: 2
name: "ECR Repository Setup"
description: "ECR repositories for frontend and backend containers"
cloudformation_stacks: []
resources:
  - type: "AWS::ECR::Repository"
    name: "sbcntr-backend-app"
    required: true
    validation_rules:
      - "ecr_encryption_enabled"
      - "ecr_image_tag_mutability"
  - type: "AWS::ECR::Repository"
    name: "sbcntr-frontend-app"
    required: true
    validation_rules:
      - "ecr_encryption_enabled"
      - "ecr_image_tag_mutability"
dependencies:
  - 1