number: 4
name: "ECS Cluster and Load Balancer"
description: "ECS Cluster, ALB, Target Groups setup"
cloudformation_stacks: []
resources:
  - type: "AWS::ECS::Cluster"
    name: "sbcntr-app"
    required: true
    validation_rules:
      - "ecs_cluster_active"
  - type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    name: "sbcntr-frontend-app"
    required: true
    validation_rules:
      - "alb_type_check"
      - "alb_scheme_internet_facing"
      - "alb_state_active"
      - "alb_ingress_security_group"
  - type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    name: "sbcntr-frontend-app-blue"
    required: true
    validation_rules:
      - "tg_protocol_check"
      - "tg_port_check"
      - "tg_target_type_check"
  - type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    name: "sbcntr-frontend-app-green"
    required: true
    validation_rules:
      - "tg_protocol_check"
      - "tg_port_check"
      - "tg_target_type_check"
  - type: "AWS::IAM::Role"
    name: "EcsInfrastructureRoleForLoadBalancers"
    required: true
    validation_rules:
      - "iam_role_exists"
      - "ecs_infrastructure_role_name"
      - "ecs_infrastructure_policy_attached"
      - "ecs_trust_relationship"
  - type: "AWS::EC2::VPCEndpoint"
    name: "sbcntr-ecr-api"
    required: true
    validation_rules:
      - "vpce_attached_to_correct_vpc"
      - "vpce_security_group_check"
      - "vpce_dns_enabled_check"
  - type: "AWS::EC2::VPCEndpoint"
    name: "sbcntr-ecr-dkr"
    required: true
    validation_rules:
      - "vpce_attached_to_correct_vpc"
      - "vpce_security_group_check"
      - "vpce_dns_enabled_check"
  - type: "AWS::EC2::VPCEndpoint"
    name: "sbcntr-s3"
    required: true
    validation_rules:
      - "vpce_attached_to_correct_vpc"
  - type: "AWS::EC2::VPCEndpoint"
    name: "sbcntr-logs"
    required: true
    validation_rules:
      - "vpce_attached_to_correct_vpc"
      - "vpce_security_group_check"
      - "vpce_dns_enabled_check"
dependencies:
  - 1
  - 2
  - 3