number: 3
name: "VPC Endpoints Setup"
description: "VPC Endpoints for ECR, S3, and CloudWatch Logs"
cloudformation_stacks: []
resources:
  - type: "AWS::EC2::VPCEndpoint"
    name: "sbcntr-ecr-api"
    required: true
    validation_rules:
      - "vpce_attached_to_correct_vpc"
      - "vpce_security_group_check"
      - "vpce_dns_enabled_check"
  - type: "AWS::EC2::VPCEndpoint"
    name: "sbcntr-ecr-dkr"
    required: true
    validation_rules:
      - "vpce_attached_to_correct_vpc"
      - "vpce_security_group_check"
      - "vpce_dns_enabled_check"
  - type: "AWS::EC2::VPCEndpoint"
    name: "sbcntr-s3"
    required: true
    validation_rules:
      - "vpce_attached_to_correct_vpc"
  - type: "AWS::EC2::VPCEndpoint"
    name: "sbcntr-logs"
    required: true
    validation_rules:
      - "vpce_attached_to_correct_vpc"
      - "vpce_security_group_check"
      - "vpce_dns_enabled_check"
dependencies:
  - 1