number: 1
name: "Network Construction"
description: "VPC, Subnets, Security Groups, Internet Gateway"
cloudformation_stacks: []
resources:
  - type: "AWS::EC2::VPC"
    name: "sbcntr-main"
    required: true
    validation_rules:
      - "vpc_cidr_check"
      - "vpc_state_available"
  - type: "AWS::EC2::Subnet"
    name: "sbcntr-public-ingress-a"
    required: true
    validation_rules:
      - "subnet_cidr_check"
      - "subnet_availability_zone"
  - type: "AWS::EC2::Subnet"
    name: "sbcntr-public-ingress-c"
    required: true
    validation_rules:
      - "subnet_cidr_check"
      - "subnet_availability_zone"
  - type: "AWS::EC2::Subnet"
    name: "sbcntr-private-app-a"
    required: true
    validation_rules:
      - "subnet_cidr_check"
      - "subnet_availability_zone"
  - type: "AWS::EC2::Subnet"
    name: "sbcntr-private-app-c"
    required: true
    validation_rules:
      - "subnet_cidr_check"
      - "subnet_availability_zone"
  - type: "AWS::EC2::SecurityGroup"
    name: "sbcntr-ingress"
    required: true
    validation_rules:
      - "sg_ingress_rules_check"
  - type: "AWS::EC2::SecurityGroup"
    name: "sbcntr-frontend-app"
    required: true
    validation_rules:
      - "sg_frontend_rules_check"
  - type: "AWS::EC2::SecurityGroup"
    name: "sbcntr-backend-app"
    required: true
    validation_rules:
      - "sg_backend_rules_check"
  - type: "AWS::EC2::InternetGateway"
    name: "sbcntr-main"
    required: true
    validation_rules:
      - "igw_attached_to_vpc"
dependencies: []