type: "AWS::ECR::Repository"
validation_rules:
  - name: "ecr_encryption_enabled"
    type: "property"
    property: "EncryptionType"
    expected: "AES256"
    operator: "eq"
    error_message: "ECR repository should have AES256 encryption enabled"
    severity: "warning"
  - name: "ecr_image_tag_mutability"
    type: "property"
    property: "ImageTagMutability"
    expected: "IMMUTABLE"
    operator: "eq"
    error_message: "ECR repository should have immutable image tags for better security"
    severity: "warning"
