type: "AWS::ECS::Cluster"
validation_rules:
  - name: "ecs_cluster_active"
    type: "property"
    property: "Status"
    expected: "ACTIVE"
    operator: "eq"
    error_message: "ECS cluster should be in ACTIVE state"
    severity: "error"
  - name: "ecs_service_running"
    type: "property"
    property: "Status"
    expected: "ACTIVE"
    operator: "eq"
    error_message: "ECS service should be in ACTIVE state"
    severity: "error"
  - name: "ecs_service_desired_count"
    type: "property"
    property: "DesiredCount"
    expected: 1
    operator: "gt"
    error_message: "ECS service should have at least 1 desired task"
    severity: "error"
  - name: "task_def_family_check"
    type: "property"
    property: "Family"
    expected: "sbcntr-"
    operator: "contains"
    error_message: "Task definition family should start with sbcntr-"
    severity: "error"
  - name: "task_def_container_check"
    type: "exists"
    property: "ContainerDefinitions"
    error_message: "Task definition should have container definitions"
    severity: "error"