type: "AWS::ECS::Service"
validation_rules:
  # ECSサービスがアクティブかチェック
  - name: "ecs_service_running"
    type: "property"
    property: "Status"
    expected: "ACTIVE"
    operator: "eq"
    error_message: "ECS service should be in ACTIVE state"
    severity: "error"

  # 起動タスク数のチェック
  - name: "ecs_service_desired_count"
    type: "property"
    property: "DesiredCount"
    expected: 1
    operator: "gte"
    error_message: "ECS service should have at least 1 desired task"
    severity: "error"

  # 実行タスク数のチェック
  - name: "ecs_service_running_count"
    type: "property"
    property: "RunningCount"
    expected: 0
    operator: "gt"
    error_message: "ECS service should have at least 1 running task"
    severity: "warning"

  # セキュリティグループが設定されているかチェック
  - name: "ecs_service_security_group_check"
    type: "count"
    property: "SecurityGroups"
    expected: 1
    operator: "ge"
    error_message: "ECS service should have at least one security group attached"
    severity: "error"

  # frontendサービス用セキュリティグループチェック
  - name: "ecs_service_frontend_security_group"
    type: "property"
    property: "SecurityGroupNames[0]"
    expected: "sbcntr-frontend-app"
    operator: "eq"
    error_message: "Frontend ECS service should have sbcntr-frontend-app security group"
    severity: "error"

  # backendサービス用セキュリティグループチェック
  - name: "ecs_service_backend_security_group"
    type: "property"
    property: "SecurityGroupNames[0]"
    expected: "sbcntr-backend-app"
    operator: "eq"
    error_message: "Backend ECS service should have sbcntr-backend-app security group"
    severity: "error"

  # サブネットが設定されているかチェック
  - name: "ecs_service_subnet_check"
    type: "count"
    property: "Subnets"
    expected: 2
    operator: "ge"
    error_message: "ECS service should be deployed in at least 2 subnets"
    severity: "error"

  # プライベートサブネットで起動しているかチェック
  - name: "ecs_service_private_subnet_check"
    type: "property"
    property: "SubnetNames[0]"

    expected: "sbcntr-private-app-"
    operator: "contains"
    error_message: "ECS service should be deployed in/ sbcntr-app subnets"
    severity: "error"

  # ヘルスチェックグレースピリオドの設定チェック
  - name: "ecs_service_health_check_grace_period"
    type: "property"
    property: "HealthCheckGracePeriodSeconds"
    expected: 0
    operator: "gt"
    error_message: "ECS service should have health check grace period configured"
    severity: "warning"

  # ロードバランサーが設定されているかチェック
  - name: "ecs_service_load_balancer_check"
    type: "count"
    property: "LoadBalancers"
    expected: 1
    operator: "ge"
    error_message: "ECS service should have at least one load balancer configured"
    severity: "warning"