type: "AWS::EC2::VPC"
validation_rules:
  - name: "vpc_cidr_check"
    type: "property"
    property: "CidrBlock"
    expected: "10.0.0.0/16"
    operator: "eq"
    error_message: "VPC CIDR block should be 10.0.0.0/16"
    severity: "error"
  - name: "vpc_state_available"
    type: "property"
    property: "State"
    expected: "available"
    operator: "eq"
    error_message: "VPC should be in available state"
    severity: "error"