type: "AWS::EC2::VPCEndpoint"
validation_rules:
  # VPCエンドポイントが正しいVPCにアタッチされているかチェック
  - name: "vpce_attached_to_correct_vpc"
    type: "property"
    property: "VpcName"
    expected: "sbcntr-main"
    operator: "eq"
    error_message: "VPC Endpoint must be attached to sbcntr-vpc"
    severity: "error"

  # セキュリティグループが正しく設定されているかチェック（Interface型エンドポイント用）
  - name: "vpce_security_group_check"
    type: "property"
    property: "SecurityGroupNames[0]"
    expected: "sbcntr-vpce"
    operator: "eq"
    error_message: "Interface VPC Endpoint should have sbcntr-private-egress security group attached"
    severity: "error"

  # DNS設定が有効になっているかチェック（Interface型エンドポイント用）
  - name: "vpce_dns_enabled_check"
    type: "property"
    property: "PrivateDnsEnabled"
    expected: true
    operator: "eq"
    error_message: "Interface VPC Endpoint should have Private DNS enabled"
    severity: "error"

  # Step7: S3用VPCエンドポイント（ゲートウェイ型）のvalidation rules
  - name: "vpce_s3_gateway_type"
    type: "property"
    property: "VpcEndpointType"
    expected: "Gateway"
    operator: "eq"
    error_message: "S3 VPC Endpoint must be Gateway type"
    severity: "error"

  - name: "vpce_s3_service_name"
    type: "property"
    property: "ServiceName"
    expected: "com.amazonaws.ap-northeast-1.s3"
    operator: "eq"
    error_message: "S3 VPC Endpoint service name must be com.amazonaws.ap-northeast-1.s3"
    severity: "error"

  - name: "vpce_s3_route_table_association"
    type: "exists"
    property: "RouteTableIds"
    error_message: "S3 VPC Endpoint must have route table associations"
    severity: "error"

  - name: "vpce_s3_vpc_association"
    type: "property"
    property: "VpcName"
    expected: "sbcntr-main"
    operator: "eq"
    error_message: "S3 VPC Endpoint must be attached to sbcntr-main VPC"
    severity: "error"

  # Step7: ECR API用VPCエンドポイント（インターフェース型）のvalidation rules
  - name: "vpce_ecr_api_interface_type"
    type: "property"
    property: "VpcEndpointType"
    expected: "Interface"
    operator: "eq"
    error_message: "ECR API VPC Endpoint must be Interface type"
    severity: "error"

  - name: "vpce_ecr_api_service_name"
    type: "property"
    property: "ServiceName"
    expected: "com.amazonaws.ap-northeast-1.ecr.api"
    operator: "eq"
    error_message: "ECR API VPC Endpoint service name must be com.amazonaws.ap-northeast-1.ecr.api"
    severity: "error"

  - name: "vpce_ecr_api_subnet_association"
    type: "exists"
    property: "SubnetIds"
    error_message: "ECR API VPC Endpoint must have subnet associations"
    severity: "error"

  - name: "vpce_ecr_api_security_group"
    type: "property"
    property: "SecurityGroupNames[0]"
    expected: "sbcntr-vpce"
    operator: "eq"
    error_message: "ECR API VPC Endpoint must have sbcntr-vpce security group attached"
    severity: "error"

  - name: "vpce_ecr_api_private_dns_enabled"
    type: "property"
    property: "PrivateDnsEnabled"
    expected: true
    operator: "eq"
    error_message: "ECR API VPC Endpoint must have Private DNS enabled"
    severity: "error"

  # Step7: ECR DKR用VPCエンドポイント（インターフェース型）のvalidation rules
  - name: "vpce_ecr_dkr_interface_type"
    type: "property"
    property: "VpcEndpointType"
    expected: "Interface"
    operator: "eq"
    error_message: "ECR DKR VPC Endpoint must be Interface type"
    severity: "error"

  - name: "vpce_ecr_dkr_service_name"
    type: "property"
    property: "ServiceName"
    expected: "com.amazonaws.ap-northeast-1.ecr.dkr"
    operator: "eq"
    error_message: "ECR DKR VPC Endpoint service name must be com.amazonaws.ap-northeast-1.ecr.dkr"
    severity: "error"

  - name: "vpce_ecr_dkr_subnet_association"
    type: "exists"
    property: "SubnetIds"
    error_message: "ECR DKR VPC Endpoint must have subnet associations"
    severity: "error"

  - name: "vpce_ecr_dkr_security_group"
    type: "property"
    property: "SecurityGroupNames[0]"
    expected: "sbcntr-vpce"
    operator: "eq"
    error_message: "ECR DKR VPC Endpoint must have sbcntr-vpce security group attached"
    severity: "error"

  - name: "vpce_ecr_dkr_private_dns_enabled"
    type: "property"
    property: "PrivateDnsEnabled"
    expected: true
    operator: "eq"
    error_message: "ECR DKR VPC Endpoint must have Private DNS enabled"
    severity: "error"

  # Step7: CloudWatch Logs用VPCエンドポイント（インターフェース型）のvalidation rules
  - name: "vpce_logs_interface_type"
    type: "property"
    property: "VpcEndpointType"
    expected: "Interface"
    operator: "eq"
    error_message: "CloudWatch Logs VPC Endpoint must be Interface type"
    severity: "error"

  - name: "vpce_logs_service_name"
    type: "property"
    property: "ServiceName"
    expected: "com.amazonaws.ap-northeast-1.logs"
    operator: "eq"
    error_message: "CloudWatch Logs VPC Endpoint service name must be com.amazonaws.ap-northeast-1.logs"
    severity: "error"

  - name: "vpce_logs_subnet_association"
    type: "exists"
    property: "SubnetIds"
    error_message: "CloudWatch Logs VPC Endpoint must have subnet associations"
    severity: "error"

  - name: "vpce_logs_security_group"
    type: "property"
    property: "SecurityGroupNames[0]"
    expected: "sbcntr-vpce"
    operator: "eq"
    error_message: "CloudWatch Logs VPC Endpoint must have sbcntr-vpce security group attached"
    severity: "error"

  - name: "vpce_logs_private_dns_enabled"
    type: "property"
    property: "PrivateDnsEnabled"
    expected: true
    operator: "eq"
    error_message: "CloudWatch Logs VPC Endpoint must have Private DNS enabled"
    severity: "error"

  # Step7: Secrets Manager用VPCエンドポイント（インターフェース型）のvalidation rules
  - name: "vpce_secretsmanager_interface_type"
    type: "property"
    property: "VpcEndpointType"
    expected: "Interface"
    operator: "eq"
    error_message: "Secrets Manager VPC Endpoint must be Interface type"
    severity: "error"

  - name: "vpce_secretsmanager_service_name"
    type: "property"
    property: "ServiceName"
    expected: "com.amazonaws.ap-northeast-1.secretsmanager"
    operator: "eq"
    error_message: "Secrets Manager VPC Endpoint service name must be com.amazonaws.ap-northeast-1.secretsmanager"
    severity: "error"

  - name: "vpce_secretsmanager_subnet_association"
    type: "exists"
    property: "SubnetIds"
    error_message: "Secrets Manager VPC Endpoint must have subnet associations"
    severity: "error"

  - name: "vpce_secretsmanager_security_group"
    type: "property"
    property: "SecurityGroupNames[0]"
    expected: "sbcntr-vpce"
    operator: "eq"
    error_message: "Secrets Manager VPC Endpoint must have sbcntr-vpce security group attached"
    severity: "error"

  - name: "vpce_secretsmanager_private_dns_enabled"
    type: "property"
    property: "PrivateDnsEnabled"
    expected: true
    operator: "eq"
    error_message: "Secrets Manager VPC Endpoint must have Private DNS enabled"
    severity: "error"
