type: "AWS::EC2::VPCEndpoint"
validation_rules:
  # VPCエンドポイントが正しいVPCにアタッチされているかチェック
  - name: "vpce_attached_to_correct_vpc"
    type: "property"
    property: "VpcName"
    expected: "sbcntr-main"
    operator: "eq"
    error_message: "VPC Endpoint must be attached to sbcntr-vpc"
    severity: "error"

  # セキュリティグループが正しく設定されているかチェック（Interface型エンドポイント用）
  - name: "vpce_security_group_check"
    type: "property"
    property: "SecurityGroupNames[0]"
    expected: "sbcntr-private-egress"
    operator: "eq"
    error_message: "Interface VPC Endpoint should have sbcntr-private-egress security group attached"
    severity: "error"

  # DNS設定が有効になっているかチェック（Interface型エンドポイント用）
  - name: "vpce_dns_enabled_check"
    type: "property"
    property: "PrivateDnsEnabled"
    expected: true
    operator: "eq"
    error_message: "Interface VPC Endpoint should have Private DNS enabled"
    severity: "error"
